[package]
name = "tetrrs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.8.5" }
getrandom = { version = "0.2.15", features = ["js"] }
macroquad = "0.4.13"
miniquad = "0.4.6"
serde_json = "1.0.137"
