name: Build and Deploy Macroquad to WASM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Add wasm32 target
      run: rustup target add wasm32-unknown-unknown

    - name: Build the Macroquad project
      run: cargo build --release --target wasm32-unknown-unknown

    - name: Move WASM to root
      run: mv target/wasm32-unknown-unknown/release/tetrrs.wasm ./tetrrs.wasm

    - name: Deploy to web branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Fetch and checkout web branch
        git fetch origin web
        git checkout web
        
        # Remove old files but DO NOT touch index.html
        rm -rf assets tetrrs.wasm
        
        # Copy new files from previous build
        cp -r ../assets .
        cp ../tetrrs.wasm .
        
        # Commit and push
        git add -A
        git commit -m "Update WASM and assets [skip ci]"
        git push origin web
        
        # Commit and push changes
        git add -A
        git commit -m "Update WASM and assets"
        git push origin web
