name: Build and Deploy Macroquad to WASM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Add wasm32 target
      run: rustup target add wasm32-unknown-unknown

    - name: Build the Macroquad project
      run: cargo build --release --target wasm32-unknown-unknown

    - name: Move WASM to root
      run: mv target/wasm32-unknown-unknown/release/tetrrs.wasm ./tetrrs.wasm

    - name: Deploy to web branch
      run: |
        # Configure git
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Create temporary directory
        mkdir temp
        
        # Fetch the web branch and check it out
        git fetch origin web
        git checkout web
        
        # Save index.html
        cp index.html temp/
        
        # Clean directory except temp
        git rm -rf *
        
        # Get new files from main
        git checkout main
        cp -r assets temp/
        cp tetrrs.wasm temp/
        
        # Switch back to web branch and update content
        git checkout web
        mv temp/* ./
        rm -rf temp
        
        # Commit and push changes
        git add -A
        git commit -m "Update WASM and assets"
        git push origin web
