name: Build and Deploy Macroquad to WASM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Add wasm32 target
      run: rustup target add wasm32-unknown-unknown

    - name: Build the Macroquad project
      run: cargo build --release --target wasm32-unknown-unknown

    - name: Verify WASM file
      run: |
        if [ ! -f target/wasm32-unknown-unknown/release/tetrrs.wasm ]; then
          echo "Error: WASM file not found!"
          exit 1
        fi

    - name: Move the WASM file
      run: cp target/wasm32-unknown-unknown/release/tetrrs.wasm .

    - name: Clean up the web branch and add necessary files
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b web
        # Remove everything except the files you want to keep
        find . -not -name '.' -not -name '.git' -not -name 'index.html' -not -name 'tetrrs.wasm' -not -name 'assets' -not -path './assets/*' -exec rm -rf {} +
        # Ensure the necessary files are present and staged for commit
        git add index.html tetrrs.wasm assets/
        git commit -m "Update WASM file"
        git push origin web --force
