name: Build and Deploy Macroquad to WASM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Add wasm32 target
      run: rustup target add wasm32-unknown-unknown

    - name: Build the Macroquad project
      run: cargo build --release --target wasm32-unknown-unknown

    - name: Move the WASM file
      run: cp target/wasm32-unknown-unknown/release/tetrrs.wasm .

    - name: Clean up the web branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b web
        git rm -rf .
        git checkout main -- index.html assets/
        git add tetrrs.wasm index.html assets/
        git commit -m "Update WASM file"
        git push origin web --force
