name: Build and Deploy Macroquad to WASM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Add wasm32 target
      run: rustup target add wasm32-unknown-unknown

    - name: Build the Macroquad project
      run: cargo build --release --target wasm32-unknown-unknown

    - name: Move WASM to root
      run: mv target/wasm32-unknown-unknown/release/tetrrs.wasm ./tetrrs.wasm

    - name: Deploy to web branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # Create a temporary directory and copy index.html
        mkdir temp
        git checkout web
        cp index.html temp/
        
        # Clean everything except the temp directory
        rm -rf assets tetrrs.wasm
        
        # Switch back to main to get new files
        git checkout main
        cp -r assets temp/
        cp tetrrs.wasm temp/
        
        # Switch to web branch and replace content
        git checkout web
        git rm -rf *
        mv temp/* ./
        rm -rf temp
        
        # Stage and commit changes
        git add -A
        git commit -m "Update WASM and assets"
        git push origin web
