name: Build and Deploy Macroquad to WASM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Add wasm32 target
      run: rustup target add wasm32-unknown-unknown

    - name: Build the Macroquad project
      run: cargo build --release --target wasm32-unknown-unknown

    - name: Move WASM to root
      run: mv target/wasm32-unknown-unknown/release/tetrrs.wasm ./tetrrs.wasm

    - name: Deploy to web branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Remove everything except what we want to deploy
        find . -mindepth 1 ! -name 'index.html' ! -name 'assets' ! -name 'tetrrs.wasm' ! -name '.git' -exec rm -rf {} +
        
        # Force push to web branch (this will overwrite web branch with exactly these files)
        git add -A
        git commit -m "Deploy game"
        git push origin main:web --force
