name: Build and Deploy Macroquad to WASM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Add wasm32 target
      run: rustup target add wasm32-unknown-unknown

    - name: Build the Macroquad project
      run: cargo build --release --target wasm32-unknown-unknown

    - name: Move WASM to root
      run: mv target/wasm32-unknown-unknown/release/tetrrs.wasm ./tetrrs.wasm

    - name: Deploy to web branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Create and switch to a clean web branch
        git checkout --orphan web
        git reset --hard
        
        # Just keep index.html, assets, and wasm
        find . -maxdepth 1 ! -name '.' ! -name '.git' ! -name 'index.html' ! -name 'tetrrs.wasm' ! -name 'assets' -exec rm -rf {} +
        
        # Add and commit
        git add -A
        echo "Files to be committed:"
        git status
        git commit -m "Deploy web build"
        
        # Force push to web branch
        git push -f origin web
        git commit -m "Deploy web build"
        
        # Force push to web branch
        git push -f origin web
